server:
  port: 8888

management:
  context-path: /admin

spring:
  cloud:
    config:
      server:
        uri: https://github.com/ehdez73/minionize-the-world-config
        basedir: /tmp/minionize-the-world-config
          
eureka:
  client:
    serviceUrl:
      defaultZone: http://Sirius:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /admin/info
    healthCheckUrlPath: /admin/health
      
      
      
secret: '{cipher}AQBunH7b87s86E/k3YaISZe90th7eOMzxv/CupLgU4BD5ERo1FD4B2S9egNtqZE9jNI1BsycyDeFN+o207S8/iVhXw4lRX8bE15jLdF537uakNFIYvBSdRx7pjNwtcorCBogqmhAQWR3ZOovWOAGhLw8MgsXAgz8oPxvIdn9Fjjd+PAofV93X7CSXEN5hgPq+s4M+oPErTQgK4KfwJu2mBjdBHqlecUMKBcaeK5dVwbqFWsAH9hmIZ/jVhSZ56uveLtCVXqrrfEne9B/WPKF4KhpKskjfPszN2wwWwjLjo7xjzasMXp3qb9t8Si4mGqLPH3mmqKsCscw61we2RIg1t8W6oJpgKzt1DA00ms8zqgUjHZyyybGDujEKp37gzOhrRw='

logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'TRACE'
    
